package org.example.commands;
import org.example.Main;
import org.example.auth.Session;
import org.example.model.*;
import java.io.BufferedReader;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

public class AddCommand implements Command {
    
    @Override
    public void execute(String[] args, BufferedReader input) throws Exception {
        // Check authentication
        var currentUser = Session.getCurrentUser();
        if (currentUser == null) {
            System.out.println("You must login first. Use 'login' command.");
            return;
        }
        
        System.out.println("Creating a new Person (owner: " + currentUser.getLogin() + ")");
        
        try {
            // Read name
            System.out.print("Name: ");
            String name = input.readLine().trim();
            if (name.isEmpty()) throw new IllegalArgumentException("Name cannot be empty");
            
            // Read Coordinates (x and y)
            System.out.print("Coordinate X (long): ");
            long coordX = Long.parseLong(input.readLine().trim());
            System.out.print("Coordinate Y (double): ");
            double coordY = Double.parseDouble(input.readLine().trim());
            Coordinates coordinates = new Coordinates(coordX, coordY);
            
            // Read height
            System.out.print("Height (float > 0): ");
            float height = Float.parseFloat(input.readLine().trim());
            
            // Read birthday (optional, can be null)
            System.out.print("Birthday (format: yyyy-MM-ddTHH:mm:ss, press Enter to skip): ");
            String birthdayStr = input.readLine().trim();
            LocalDateTime birthday = null;
            if (!birthdayStr.isEmpty()) {
                try {
                    birthday = LocalDateTime.parse(birthdayStr, DateTimeFormatter.ISO_LOCAL_DATE_TIME);
                } catch (DateTimeParseException e) {
                    System.out.println("Invalid date format. Setting birthday to null.");
                }
            }
            
            // Read hair color (enum)
            System.out.println("Hair Color options: " + java.util.Arrays.asList(Color.values()));
            System.out.print("Hair Color: ");
            String hairColorStr = input.readLine().trim().toUpperCase();
            Color hairColor = Color.valueOf(hairColorStr);
            
            // Read nationality (enum)
            System.out.println("Nationality options: " + java.util.Arrays.asList(Country.values()));
            System.out.print("Nationality: ");
            String nationalityStr = input.readLine().trim().toUpperCase();
            Country nationality = Country.valueOf(nationalityStr);
            
            // Read Location (x, y, z)
            System.out.print("Location X (double): ");
            double locX = Double.parseDouble(input.readLine().trim());
            System.out.print("Location Y (Double): ");
            Double locY = Double.parseDouble(input.readLine().trim());
            System.out.print("Location Z (Integer): ");
            Integer locZ = Integer.parseInt(input.readLine().trim());
            Location location = new Location(locX, locY, locZ);
            
            // Create Person object (ID will be generated by CollectionManager)
            Person person = new Person(name, coordinates, height, birthday, hairColor, nationality, location);
            
            // Add to collection with current user's ID as owner
            Main.collectionManager.addPerson(person, currentUser.getId());
            System.out.println("Person added successfully with ID: " + person.getId() + " (owner ID: " + currentUser.getId() + ")");
            
        } catch (NumberFormatException e) {
            System.out.println("Invalid number format: " + e.getMessage());
        } catch (IllegalArgumentException e) {
            System.out.println("Invalid input: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Error creating person: " + e.getMessage());
        }
    }
}